version: 2
updates:
  # Backend Services (Gradle)
  - package-ecosystem: "gradle"
    directory: "/beeja-services/beeja-finance"
    schedule:
      interval: "daily"
      time: "12:30"
      timezone: "Asia/Kolkata"

  - package-ecosystem: "gradle"
    directory: "/beeja-services/beeja-expense"
    schedule:
      interval: "daily"
      time: "12:30"
      timezone: "Asia/Kolkata"

  - package-ecosystem: "docker"
    directory: "/beeja-services/beeja-accounts"  
    schedule:
      interval: "daily"
      time: "12:30"
      timezone: "Asia/Kolkata"
