version: 2
updates:
  # Backend Services (Gradle)
  - package-ecosystem: "gradle"
    directory: "/beeja-services/beeja-cloud-gateway"
    schedule:
      interval: "daily"
      time: "11:00"

  - package-ecosystem: "gradle"
    directory: "/beeja-services/beeja-file-management"
    schedule:
      interval: "daily"
      time: "11:00"

  - package-ecosystem: "docker"
    directory: "/beeja-services/beeja-accounts"  
    schedule:
      interval: "daily"
      time: "11:00"
