server:
  servlet:
    context-path: /notifications
  port: 8093

sendgrid-keys:
  beeja: <key>

spring:
  output:
    ansi:
      enabled: ALWAYS
  application:
    name: notification-service
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/?replicaSet=rs0&directConnection=true
      database: notifications_sbox

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

# actuator
management:
  endpoints.web.exposure.include: health,info
  info.env.enabled: true
info:
  application.name: ${spring.application.name}

client-urls:
  accountsService: http://localhost:8080/accounts

logging:
  level:
    feign=DEBUG: